using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class UI_ToolPanel : MonoBehaviour
{
    public GameObject panel_ToolPanel1;
    public GameObject panel_ToolPanel2;

    public void Init() 
    {
        Hide();




    }

    public void Show() 
    { 
        gameObject.SetActive(true); 
    }
    public void Hide() 
    { 
        gameObject.SetActive(false); 
    }
    private void Awake()
    {

    }
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
